spring.application.name=mongoAndSql

server.port=8080

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/userdb
spring.datasource.username=root
spring.datasource.password=Test
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate (for MySQL)
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/mongoUserdb

